plugins:
  enable_category_experts:
    default: true
    client: true
  show_category_expert_advanced_search_filters:
    default: true
    client: true
  category_expert_suggestion_threshold:
    default: 3
    min: 1
  category_experts_posts_require_approval:
    default: false
    client: true
  send_category_experts_reminder_pms:
    default: false
  send_admin_category_experts_posts_reminder_pm:
    default: false
  approve_past_posts_on_becoming_category_expert:
    default: false
  category_experts_topic_list_link_to_posts:
    default: false
    client: true
  max_category_expert_endorsements_per_day:
    default: 1
    min: 1
  tl2_additional_category_expert_endorsements_per_day_multiplier:
    default: 2
    min: 1
  tl3_additional_category_expert_endorsements_per_day_multiplier:
    default: 2
    min: 1
  tl4_additional_category_expert_endorsements_per_day_multiplier:
    default: 3
    min: 1
